### PR TITLE
Update README.md instructions for setting up JDK version

### PR DESCRIPTION
**Pull request by tjtanjin**
Add new instructions for setting up JDK version as the previous one is outdated

### CODE REVIEW

**Review by damithc — COMMENTED** [review]
Thanks for the PR @tjtanjin 
Which OS and which Intellij is this based on? My Intellij is relatively new v2020.2.3 (on Windows) and it matches the original instructions.

**Comment by tjtanjin** [comment]
Hello Prof!

Thank you for the reply. I am on Intellij v2020.3.1 across Windows 10, MacOS Big Sur and Ubuntu 18.0.4 (the latter 2 are fresh installations). I could not find the buttons stated in the original instructions and hence referred to [this website](https://www.jetbrains.com/help/idea/project-settings-and-structure.html#project-sdk). Is it also possible that certain settings (perhaps toolbars) have changed?

**Comment by damithc** [comment]
> Thank you for the reply. I am on Intellij v2020.3.1 across Windows 10, MacOS Big Sur and Ubuntu 18.0.4 (the latter 2 are fresh installations). I could not find the buttons stated in the original instructions and hence referred to [this website](https://www.jetbrains.com/help/idea/sdk.html#set-up-jdk). Is it also possible that certain settings (perhaps toolbars) have changed?

You are right @tjtanjin , they have changed the steps in the latest version :-p
As some other things needed changes as well, I have updated README.md myself. Can you check if [these new instructions](https://github.com/nus-cs2103-AY2021S2/ip/blob/master/README.md) work?

**Comment by tjtanjin** [comment]
Hi Prof @damithc, the new instructions work just fine :D On a side note, the <kbd>OK</kbd> button in step 2.ii only appears for Windows and Ubuntu users - Mac users see another <kbd>OPEN</kbd> button when choosing the directory (but it's not a big deal since instructions are still clear). Thank you!

**Comment by damithc** [comment]
> Hi Prof @damithc, the new instructions work just fine :D On a side note, the OK button in step 2.ii only appears for Windows and Ubuntu users - Mac users see another OPEN button when choosing the directory (but it's not a big deal since instructions are still clear). Thank you!

Great. Thanks for checking @tjtanjin

**Pull request closed without merging**
